server:
  port: 8001

spring:
  datasource:
    username: root
    password: 123321
    url: jdbc:mysql://localhost:3306/mall?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: DataHikariCP
      minimum-idle: 5
      maximum-pool-size: 50
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect